#Configure the Server Port
server:
  port: 7002
  
spring:  application:
   name: DEPARTMENT-SERVICE 
  datasource:    driver-class-name: com.mysql.jdbc.Driver    url: jdbc:mysql://localhost:3306/sbdb
    username: root
    password: root

      
eureka:
  client:
    register-with-eureka: true 
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka 
  instance:    hostname: localhost